apiVersion: v1
kind: Secret
metadata:
  name: remotecluster
  namespace: <namespace where Velero is installed>
type: Opaque
data:
  host: <base64 encoded host URL>
  sa-token: <base64 encoded service account token here>
  kubeconfig: <base64 encoded kubeconfig here>
  https_proxy: <base64 encoded https_proxy with the http://<address>:<port> format>
